
import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter, Roboto, Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import NavbarTest from '@/components/navbar/NavBarTest'
import { ThemeProvider } from '@/context/ThemeContext'
import AuthProvider from '@/context/AuthProvider'
const poppins = Poppins({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Buenas Nextjs Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={poppins.className}>
          <ThemeProvider>
            <AuthProvider>
              <div className='container'>
                <Navbar />
                  {children}
                <Footer />
              </div>
            </AuthProvider>
          </ThemeProvider>
        </body>
    </html>
  )
}
