version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_database
    environment:
      POSTGRES_USER: george
      POSTGRES_PASSWORD: kibe1234
      POSTGRES_DB: school-management
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: